version: '3.8'

services:
  spring-boot-test:
    container_name: spring-boot-test
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port for sending emails
      - "8025:8025"  # Web interface port for viewing emails
    environment:
      MH_STORAGE: maildir